name: Deploy Raven Backend

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        type: choice
        options:
          - prod
          - test

jobs:
  deploy-backend-prod:
    runs-on: self-hosted
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Ensure network exists
        uses: ./.github/actions/docker-network
        with:
          network-name: 'raven-prod'

      - name: Build and Deploy Backend
        uses: ./.github/actions/build-deploy-docker
        with:
          container-name: 'raven-prod-backend'
          network-name: 'raven-prod'
          dockerfile-path: 'backend/Dockerfile'
          build-context: 'backend'
          image-name: 'raven-backend'
          image-tag: 'prod-${{ github.sha }}'
          exposed-port: '8443:8443'