name: Deploy Raven Frontend

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        type: choice
        options:
          - prod
          - test

jobs:
  deploy-frontend-prod:
    runs-on: self-hosted
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Ensure network exists
        uses: ./.github/actions/docker-network
        with:
          network-name: 'raven-prod'

      - name: Build and Deploy Frontend
        uses: ./.github/actions/build-deploy-docker
        with:
          container-name: 'raven-prod-frontend'
          network-name: 'raven-prod'
          dockerfile-path: 'frontend/Dockerfile'
          build-context: 'frontend'
          image-name: 'raven-frontend'
          image-tag: 'prod-${{ github.sha }}'
          exposed-port: '443:443'