name: Build Workflow for RAVEN Front-End - TEST environment

on:
  push:
    branches:
      - main
      - feature/*
    paths:
      - 'frontend/**'

jobs:
  raven-frontend-build-test:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -f frontend/Dockerfile-test -t hello-raven .

      - name: Stop running containers
        run: docker stop hello-raven

      - name: Remove old containers
        run: docker rm hello-raven

      - name: Run new container
        run:  docker run -d --name hello-raven hello-raven
