name: Build Workflow for RAVEN Front-End - TEST environment

on:
  push:
    branches:
      - main
      - feature/*
    paths:
      - 'frontend/**'

jobs:
  raven-frontend-build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -f frontend/Dockerfile-test -t hello-raven .

      - name: Deploy to server via SSH
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
        run: |
          echo "$SSH_KEY" > private_key
          chmod 600 private_key

          ssh -i private_key -o StrictHostKeyChecking=yes $SSH_USER@$SSH_HOST << 'EOF'
            docker stop hello-raven || true
            docker rm hello-raven || true
            docker run -d --name hello-raven -p 443:80 hello-raven
          EOF
