name: Build Workflow for RAVEN Front-End - TEST environment

on:
  push:
    branches:
      - main
      - feature/*
    paths:
      - 'frontend/**'

jobs:
  raven-frontend-build-test:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -f frontend/Dockerfile-test -t hello-raven .

      - name: Deploy locally
        run: docker stop hello-raven || true
              docker rm hello-raven || true
              docker run -d \
                --name hello-raven \
                -p 443:80 \
                hello-raven
